/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mmse.insurance.view;

import com.mmse.insurance.control.Controller;
import com.mmse.insurance.model.entities.Claim;
import javax.swing.JFrame;

/**
 *
 * @author Adam
 */
public class AssesSevernessForm extends javax.swing.JPanel {
    Controller controller;
    Claim claim;

    /**
     * Creates new form AssesSevernessForm
     */
    public AssesSevernessForm(Controller controller, Claim claim) {
        this.claim = claim;
        this.controller = controller;
        
        initComponents();
        severeCheckBox.setSelected(claim.isSevere());
    }
    private void close(){        
        JFrame parentFrame = (JFrame) this.getParent().getParent().getParent();
        parentFrame.dispose();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        severeCheckBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        severeCheckBox.setText("Severe");
        severeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                severeCheckBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(severeCheckBox)
                    .addComponent(jButton1))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(severeCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void severeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_severeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_severeCheckBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       controller.getModel().getDb().setClaimSeverness(claim, severeCheckBox.isSelected());
       close();
       controller.resetView();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox severeCheckBox;
    // End of variables declaration//GEN-END:variables
}
