package com.mmse.insurance.view;

import java.util.Set;

import com.mmse.insurance.control.Controller;
import com.mmse.insurance.model.entities.Claim;

/**
 *
 * @author Adam
 */
@SuppressWarnings("serial")
public class ClaimsViewForm extends javax.swing.JPanel {

    private Controller controller;

    /**
     * Creates new form claimsViewForm
     */
    public ClaimsViewForm(Controller controller) {
        this.controller = controller;
        initComponents();
    }
    
    public void setClaims(Set<Claim> claimsByCustomer) {
        ((ClaimTableModel)jTable1.getModel()).setClaims(claimsByCustomer);
    }
    
    public void refresh(){
        jTable1.addNotify();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new ClaimTableModel(controller.getModel().getDb().getAllClaims()));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, Short.MAX_VALUE)
        );        
        
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
